/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

// mis paquetes
import utils.Placeholder;

/**
 *
 * @author JESUS DANIEL
 */
public class RegistrerUI extends javax.swing.JFrame {

    /**
     * Creates new form RegistrerUI
     */
    public RegistrerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrar_buttonGroup_sexo = new javax.swing.ButtonGroup();
        jPanel_registrarse = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        login_txt_usuario = new javax.swing.JTextField();
        login_lbl_usuario = new javax.swing.JLabel();
        login_lbl_usuario1 = new javax.swing.JLabel();
        login_txt_usuario1 = new javax.swing.JTextField();
        login_lbl_usuario2 = new javax.swing.JLabel();
        login_lbl_usuario3 = new javax.swing.JLabel();
        login_txt_usuario3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        login_lbl_usuario4 = new javax.swing.JLabel();
        login_txt_usuario4 = new javax.swing.JTextField();
        login_lbl_usuario5 = new javax.swing.JLabel();
        registrarse_txt_email = new javax.swing.JTextField();
        login_lbl_usuario6 = new javax.swing.JLabel();
        login_txt_usuario6 = new javax.swing.JTextField();
        login_txt_usuario7 = new javax.swing.JTextField();
        login_lbl_usuario7 = new javax.swing.JLabel();
        registrarse_btn_registrarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(771, 452));
        setResizable(false);

        jPanel_registrarse.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manager");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Project");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("V. 1.0.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)))
                        .addGap(62, 62, 62))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        login_txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_txt_usuarioActionPerformed(evt);
            }
        });

        login_lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario.setText("Nombre:");

        login_lbl_usuario1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario1.setText("Edad:");

        login_txt_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_txt_usuario1ActionPerformed(evt);
            }
        });

        login_lbl_usuario2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario2.setText("Sexo:");

        login_lbl_usuario3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario3.setText("Titulo:");

        login_txt_usuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_txt_usuario3ActionPerformed(evt);
            }
        });

        registrar_buttonGroup_sexo.add(jRadioButton1);
        jRadioButton1.setText("Masculino");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        registrar_buttonGroup_sexo.add(jRadioButton2);
        jRadioButton2.setText("Femenino");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        registrar_buttonGroup_sexo.add(jRadioButton3);
        jRadioButton3.setText("No binario");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        login_lbl_usuario4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario4.setText("Dependencia:");

        login_txt_usuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_txt_usuario4ActionPerformed(evt);
            }
        });

        login_lbl_usuario5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario5.setText("Email:");

        registrarse_txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarse_txt_emailActionPerformed(evt);
            }
        });

        login_lbl_usuario6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario6.setText("Contraseña:");

        login_txt_usuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_txt_usuario6ActionPerformed(evt);
            }
        });

        login_txt_usuario7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_txt_usuario7ActionPerformed(evt);
            }
        });

        login_lbl_usuario7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario7.setText("Validar constraseña");

        registrarse_btn_registrarse.setBackground(new java.awt.Color(255, 255, 255));
        registrarse_btn_registrarse.setText("Registrarte");
        registrarse_btn_registrarse.setPreferredSize(new java.awt.Dimension(100, 30));
        registrarse_btn_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarse_btn_registrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registrarseLayout = new javax.swing.GroupLayout(jPanel_registrarse);
        jPanel_registrarse.setLayout(jPanel_registrarseLayout);
        jPanel_registrarseLayout.setHorizontalGroup(
            jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_registrarseLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login_lbl_usuario)
                    .addComponent(login_lbl_usuario1)
                    .addComponent(login_lbl_usuario2)
                    .addComponent(login_lbl_usuario3)
                    .addComponent(login_lbl_usuario4)
                    .addComponent(login_lbl_usuario5)
                    .addComponent(login_lbl_usuario6)
                    .addComponent(login_lbl_usuario7))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarse_btn_registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login_txt_usuario4)
                    .addGroup(jPanel_registrarseLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2)
                        .addGap(58, 58, 58)
                        .addComponent(jRadioButton3))
                    .addComponent(login_txt_usuario1)
                    .addComponent(login_txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(login_txt_usuario3)
                    .addComponent(registrarse_txt_email)
                    .addComponent(login_txt_usuario6)
                    .addComponent(login_txt_usuario7))
                .addGap(61, 61, 61)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_registrarseLayout.setVerticalGroup(
            jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_registrarseLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_txt_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario1))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_lbl_usuario2)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_lbl_usuario3)
                    .addComponent(login_txt_usuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_lbl_usuario4)
                    .addComponent(login_txt_usuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_lbl_usuario5)
                    .addComponent(registrarse_txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_txt_usuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario6))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_txt_usuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarse_btn_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        utils.Placeholder.addPlaceholder(registrarse_txt_email, "emailusuario@projects.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_txt_usuarioActionPerformed

    private void login_txt_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_txt_usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_txt_usuario1ActionPerformed

    private void login_txt_usuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_txt_usuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_txt_usuario3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void login_txt_usuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_txt_usuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_txt_usuario4ActionPerformed

    private void registrarse_txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarse_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarse_txt_emailActionPerformed

    private void login_txt_usuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_txt_usuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_txt_usuario6ActionPerformed

    private void login_txt_usuario7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_txt_usuario7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_txt_usuario7ActionPerformed

    private void registrarse_btn_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarse_btn_registrarseActionPerformed
        // Acciones del boton registrarse
        
        LoginUI loginUi = new LoginUI();
        loginUi.setVisible(true);
        dispose();

    }//GEN-LAST:event_registrarse_btn_registrarseActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_registrarse;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel login_lbl_usuario;
    private javax.swing.JLabel login_lbl_usuario1;
    private javax.swing.JLabel login_lbl_usuario2;
    private javax.swing.JLabel login_lbl_usuario3;
    private javax.swing.JLabel login_lbl_usuario4;
    private javax.swing.JLabel login_lbl_usuario5;
    private javax.swing.JLabel login_lbl_usuario6;
    private javax.swing.JLabel login_lbl_usuario7;
    private javax.swing.JTextField login_txt_usuario;
    private javax.swing.JTextField login_txt_usuario1;
    private javax.swing.JTextField login_txt_usuario3;
    private javax.swing.JTextField login_txt_usuario4;
    private javax.swing.JTextField login_txt_usuario6;
    private javax.swing.JTextField login_txt_usuario7;
    private javax.swing.ButtonGroup registrar_buttonGroup_sexo;
    private javax.swing.JButton registrarse_btn_registrarse;
    private javax.swing.JTextField registrarse_txt_email;
    // End of variables declaration//GEN-END:variables
}
