/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

// mis paquetes
import logic.RegisterLogic;
import utils.Utilidades;
/**
 *
 * @author JESUS DANIEL
 */
public class RegistrerUI extends javax.swing.JFrame {

    /**
     * Creates new form RegistrerUI
     */
    public RegistrerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrar_buttonGroup_sexo = new javax.swing.ButtonGroup();
        jPanel_registrarse = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registrar_txt_nombre = new javax.swing.JTextField();
        login_lbl_usuario = new javax.swing.JLabel();
        login_lbl_usuario1 = new javax.swing.JLabel();
        registrar_txt_edad = new javax.swing.JTextField();
        login_lbl_usuario2 = new javax.swing.JLabel();
        login_lbl_usuario3 = new javax.swing.JLabel();
        registrar_txt_titulo = new javax.swing.JTextField();
        login_jRadioButton_masculino = new javax.swing.JRadioButton();
        login_jRadioButton_femenino = new javax.swing.JRadioButton();
        login_jRadioButton_noBinario = new javax.swing.JRadioButton();
        login_lbl_usuario4 = new javax.swing.JLabel();
        registrar_txt_dependencia = new javax.swing.JTextField();
        login_lbl_usuario5 = new javax.swing.JLabel();
        registrar_txt_cedula = new javax.swing.JTextField();
        login_lbl_usuario6 = new javax.swing.JLabel();
        registrar_txt_contrasegnia = new javax.swing.JTextField();
        registrar_txt_validarContrasegnia = new javax.swing.JTextField();
        login_lbl_usuario7 = new javax.swing.JLabel();
        registrar_btn_registrarte = new javax.swing.JButton();
        proyectos_btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(771, 452));
        setResizable(false);

        jPanel_registrarse.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manager");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Project");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("V. 1.0.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)))
                        .addGap(62, 62, 62))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        registrar_txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_txt_nombreActionPerformed(evt);
            }
        });

        login_lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario.setText("Nombre:");

        login_lbl_usuario1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario1.setText("Edad:");

        registrar_txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_txt_edadActionPerformed(evt);
            }
        });

        login_lbl_usuario2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario2.setText("Sexo:");

        login_lbl_usuario3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario3.setText("Titulo:");

        registrar_txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_txt_tituloActionPerformed(evt);
            }
        });

        registrar_buttonGroup_sexo.add(login_jRadioButton_masculino);
        login_jRadioButton_masculino.setText("Masculino");
        login_jRadioButton_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jRadioButton_masculinoActionPerformed(evt);
            }
        });

        registrar_buttonGroup_sexo.add(login_jRadioButton_femenino);
        login_jRadioButton_femenino.setText("Femenino");
        login_jRadioButton_femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jRadioButton_femeninoActionPerformed(evt);
            }
        });

        registrar_buttonGroup_sexo.add(login_jRadioButton_noBinario);
        login_jRadioButton_noBinario.setText("No binario");
        login_jRadioButton_noBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jRadioButton_noBinarioActionPerformed(evt);
            }
        });

        login_lbl_usuario4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario4.setText("Dependencia:");

        registrar_txt_dependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_txt_dependenciaActionPerformed(evt);
            }
        });

        login_lbl_usuario5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario5.setText("Cedula:");

        registrar_txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_txt_cedulaActionPerformed(evt);
            }
        });

        login_lbl_usuario6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario6.setText("Contraseña:");

        registrar_txt_contrasegnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_txt_contrasegniaActionPerformed(evt);
            }
        });

        registrar_txt_validarContrasegnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_txt_validarContrasegniaActionPerformed(evt);
            }
        });

        login_lbl_usuario7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario7.setText("Validar constraseña");

        registrar_btn_registrarte.setBackground(new java.awt.Color(255, 255, 255));
        registrar_btn_registrarte.setText("Registrarte");
        registrar_btn_registrarte.setPreferredSize(new java.awt.Dimension(100, 30));
        registrar_btn_registrarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_btn_registrarteActionPerformed(evt);
            }
        });

        proyectos_btn_regresar.setBackground(new java.awt.Color(255, 255, 255));
        proyectos_btn_regresar.setText("<<<");
        proyectos_btn_regresar.setPreferredSize(new java.awt.Dimension(100, 30));
        proyectos_btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proyectos_btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registrarseLayout = new javax.swing.GroupLayout(jPanel_registrarse);
        jPanel_registrarse.setLayout(jPanel_registrarseLayout);
        jPanel_registrarseLayout.setHorizontalGroup(
            jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registrarseLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login_lbl_usuario)
                    .addComponent(login_lbl_usuario1)
                    .addComponent(login_lbl_usuario2)
                    .addComponent(login_lbl_usuario3)
                    .addComponent(login_lbl_usuario4)
                    .addComponent(login_lbl_usuario5)
                    .addComponent(login_lbl_usuario6)
                    .addComponent(login_lbl_usuario7))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_registrarseLayout.createSequentialGroup()
                        .addComponent(registrar_btn_registrarte, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proyectos_btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registrar_txt_dependencia)
                    .addGroup(jPanel_registrarseLayout.createSequentialGroup()
                        .addComponent(login_jRadioButton_masculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(login_jRadioButton_femenino)
                        .addGap(58, 58, 58)
                        .addComponent(login_jRadioButton_noBinario))
                    .addComponent(registrar_txt_edad)
                    .addComponent(registrar_txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(registrar_txt_titulo)
                    .addComponent(registrar_txt_cedula)
                    .addComponent(registrar_txt_contrasegnia)
                    .addComponent(registrar_txt_validarContrasegnia))
                .addGap(61, 61, 61)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_registrarseLayout.setVerticalGroup(
            jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_registrarseLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar_txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario1))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_lbl_usuario2)
                    .addComponent(login_jRadioButton_masculino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_jRadioButton_femenino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_jRadioButton_noBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_lbl_usuario3)
                    .addComponent(registrar_txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_lbl_usuario4)
                    .addComponent(registrar_txt_dependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_lbl_usuario5)
                    .addComponent(registrar_txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar_txt_contrasegnia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario6))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar_txt_validarContrasegnia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar_btn_registrarte, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proyectos_btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        login_jRadioButton_masculino.setActionCommand("Masculino");
        login_jRadioButton_femenino.setActionCommand("Femenino");
        login_jRadioButton_noBinario.setActionCommand("No binario");
        utils.Utilidades.agregarPlaceholder(registrar_txt_cedula, "Ej. 1062959671");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrar_txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrar_txt_nombreActionPerformed

    private void registrar_txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrar_txt_edadActionPerformed

    private void registrar_txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrar_txt_tituloActionPerformed

    private void login_jRadioButton_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_jRadioButton_masculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_jRadioButton_masculinoActionPerformed

    private void login_jRadioButton_femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_jRadioButton_femeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_jRadioButton_femeninoActionPerformed

    private void login_jRadioButton_noBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_jRadioButton_noBinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_jRadioButton_noBinarioActionPerformed

    private void registrar_txt_dependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_txt_dependenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrar_txt_dependenciaActionPerformed

    private void registrar_txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_txt_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrar_txt_cedulaActionPerformed

    private void registrar_txt_contrasegniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_txt_contrasegniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrar_txt_contrasegniaActionPerformed

    private void registrar_txt_validarContrasegniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_txt_validarContrasegniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrar_txt_validarContrasegniaActionPerformed

    private void registrar_btn_registrarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_btn_registrarteActionPerformed
        // Acciones del boton registrarse
        
        // Capturar los datos del usuario
       String nombre = registrar_txt_nombre.getText();
       String edadText = registrar_txt_edad.getText();
       String sexo = Utilidades.obtenerTextoRadioButtonSeleccionado(registrar_buttonGroup_sexo);
       String titulo = registrar_txt_titulo.getText();
       String dependencia = registrar_txt_dependencia.getText();
       String cedula = registrar_txt_cedula.getText();
       String contrasegnia = registrar_txt_contrasegnia.getText();
       String validarContrasegnia = registrar_txt_validarContrasegnia.getText();
       
       // Intentar registrar el usuario
        int registrado = RegisterLogic.registrarUsuario(nombre, edadText, sexo, titulo, dependencia, cedula, contrasegnia, validarContrasegnia);
        
        // Validamos la acción
        if(registrado == 1) {
            Utilidades.mostrarVentana("Registro exitoso.", "Registrado");
            
            // Regresar al login.
            LoginUI loginUi = new LoginUI();
            loginUi.setVisible(true);
            dispose();
        }
    
    }//GEN-LAST:event_registrar_btn_registrarteActionPerformed

    private void proyectos_btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proyectos_btn_regresarActionPerformed
        // Acciones del boton cerrar sesion

        LoginUI LoginUi = new LoginUI();
        LoginUi.setVisible(true);
        dispose();
    }//GEN-LAST:event_proyectos_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_registrarse;
    private javax.swing.JRadioButton login_jRadioButton_femenino;
    private javax.swing.JRadioButton login_jRadioButton_masculino;
    private javax.swing.JRadioButton login_jRadioButton_noBinario;
    private javax.swing.JLabel login_lbl_usuario;
    private javax.swing.JLabel login_lbl_usuario1;
    private javax.swing.JLabel login_lbl_usuario2;
    private javax.swing.JLabel login_lbl_usuario3;
    private javax.swing.JLabel login_lbl_usuario4;
    private javax.swing.JLabel login_lbl_usuario5;
    private javax.swing.JLabel login_lbl_usuario6;
    private javax.swing.JLabel login_lbl_usuario7;
    private javax.swing.JButton proyectos_btn_regresar;
    private javax.swing.JButton registrar_btn_registrarte;
    private javax.swing.ButtonGroup registrar_buttonGroup_sexo;
    private javax.swing.JTextField registrar_txt_cedula;
    private javax.swing.JTextField registrar_txt_contrasegnia;
    private javax.swing.JTextField registrar_txt_dependencia;
    private javax.swing.JTextField registrar_txt_edad;
    private javax.swing.JTextField registrar_txt_nombre;
    private javax.swing.JTextField registrar_txt_titulo;
    private javax.swing.JTextField registrar_txt_validarContrasegnia;
    // End of variables declaration//GEN-END:variables
}
