/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.proyectos;

import javax.swing.JOptionPane;
import logic.proyectos.ProyectosCrearLogic;
import ui.HomeUI;

/**
 *
 * @author JESUS DANIEL
 */
public class ProyectosCrearUI extends javax.swing.JFrame {

    /**
     * Creates new form CrearProyecto
     */
    private String cedulaUsuario;
    public ProyectosCrearUI(String cedula) {
        cedulaUsuario = cedula;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        login_lbl_usuario = new javax.swing.JLabel();
        crear_proyecto_btn_crear_proyecto = new javax.swing.JButton();
        crear_proyecto_txt_nombre = new javax.swing.JTextField();
        login_lbl_usuario1 = new javax.swing.JLabel();
        crear_proyecto_txt_fecha_inicio = new javax.swing.JTextField();
        login_lbl_usuario2 = new javax.swing.JLabel();
        crear_proyecto_txt_duracion = new javax.swing.JTextField();
        crear_proyecto_txt_presupuesto = new javax.swing.JTextField();
        login_lbl_usuario3 = new javax.swing.JLabel();
        login_lbl_usuario4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        crear_proyecto_jTextArea_descripcion = new javax.swing.JTextArea();
        crear_proyecto_btn_regresar = new javax.swing.JButton();
        login_lbl_usuario5 = new javax.swing.JLabel();
        crear_proyecto_txt_id_proyecto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manager");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Project");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("V. 1.0.0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Crear Proyecto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(51, 51, 51))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(76, 76, 76)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        login_lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario.setText("Nombre:");

        crear_proyecto_btn_crear_proyecto.setBackground(new java.awt.Color(255, 255, 255));
        crear_proyecto_btn_crear_proyecto.setText("Crear Proyecto");
        crear_proyecto_btn_crear_proyecto.setPreferredSize(new java.awt.Dimension(100, 30));
        crear_proyecto_btn_crear_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_proyecto_btn_crear_proyectoActionPerformed(evt);
            }
        });

        crear_proyecto_txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_proyecto_txt_nombreActionPerformed(evt);
            }
        });

        login_lbl_usuario1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario1.setText("Fecha Inicio:");

        crear_proyecto_txt_fecha_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_proyecto_txt_fecha_inicioActionPerformed(evt);
            }
        });

        login_lbl_usuario2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario2.setText("Duracion:");

        crear_proyecto_txt_duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_proyecto_txt_duracionActionPerformed(evt);
            }
        });

        crear_proyecto_txt_presupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_proyecto_txt_presupuestoActionPerformed(evt);
            }
        });

        login_lbl_usuario3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario3.setText("Presupuesto:");

        login_lbl_usuario4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario4.setText("Descripción:");

        crear_proyecto_jTextArea_descripcion.setColumns(20);
        crear_proyecto_jTextArea_descripcion.setRows(5);
        jScrollPane1.setViewportView(crear_proyecto_jTextArea_descripcion);

        crear_proyecto_btn_regresar.setBackground(new java.awt.Color(255, 255, 255));
        crear_proyecto_btn_regresar.setText("<<<");
        crear_proyecto_btn_regresar.setPreferredSize(new java.awt.Dimension(100, 30));
        crear_proyecto_btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_proyecto_btn_regresarActionPerformed(evt);
            }
        });

        login_lbl_usuario5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_lbl_usuario5.setText("ID Proyecto:");

        crear_proyecto_txt_id_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_proyecto_txt_id_proyectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(login_lbl_usuario1)
                                .addGap(18, 18, 18)
                                .addComponent(crear_proyecto_txt_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(login_lbl_usuario)
                                .addGap(18, 18, 18)
                                .addComponent(crear_proyecto_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(login_lbl_usuario2)
                                .addGap(18, 18, 18)
                                .addComponent(crear_proyecto_txt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(login_lbl_usuario3)
                                .addGap(18, 18, 18)
                                .addComponent(crear_proyecto_txt_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(login_lbl_usuario4)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(crear_proyecto_btn_crear_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(124, 124, 124)
                                    .addComponent(crear_proyecto_btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(login_lbl_usuario5)
                        .addGap(18, 18, 18)
                        .addComponent(crear_proyecto_txt_id_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_proyecto_txt_id_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_proyecto_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_proyecto_txt_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_proyecto_txt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_proyecto_txt_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lbl_usuario3))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_lbl_usuario4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_proyecto_btn_crear_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crear_proyecto_btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void crear_proyecto_btn_crear_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_proyecto_btn_crear_proyectoActionPerformed
       // Acciones del botón "Crear Proyecto"

    // Capturar los datos del proyecto
    String idProyecto = crear_proyecto_txt_id_proyecto.getText();
    String nombre = crear_proyecto_txt_nombre.getText();
    String duracion = crear_proyecto_txt_duracion.getText();
    String descripcion = crear_proyecto_jTextArea_descripcion.getText();
    String fechaInicio = crear_proyecto_txt_fecha_inicio.getText();
    String presupuesto = crear_proyecto_txt_presupuesto.getText();

    // Intentar crear el proyecto
    int creado = ProyectosCrearLogic.crearProyecto(idProyecto, nombre, duracion, descripcion, cedulaUsuario, fechaInicio,  presupuesto);

    // Validar el resultado y mostrar un mensaje al usuario
    if (creado == 1) {
        JOptionPane.showMessageDialog(null, "Proyecto creado con éxito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

        // Cerrar esta ventana y mostrar la ventana principal (Home)
        HomeUI home = new HomeUI(cedulaUsuario);
        home.setVisible(true);
        dispose();
    }

    
    }//GEN-LAST:event_crear_proyecto_btn_crear_proyectoActionPerformed

    private void crear_proyecto_txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_proyecto_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crear_proyecto_txt_nombreActionPerformed

    private void crear_proyecto_txt_fecha_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_proyecto_txt_fecha_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crear_proyecto_txt_fecha_inicioActionPerformed

    private void crear_proyecto_txt_duracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_proyecto_txt_duracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crear_proyecto_txt_duracionActionPerformed

    private void crear_proyecto_txt_presupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_proyecto_txt_presupuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crear_proyecto_txt_presupuestoActionPerformed

    private void crear_proyecto_btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_proyecto_btn_regresarActionPerformed
        // Acciones del boton regresar

       // Cerrar esta ventana y mostrar la ventana principal (Home)
        HomeUI home = new HomeUI(cedulaUsuario);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_crear_proyecto_btn_regresarActionPerformed

    private void crear_proyecto_txt_id_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_proyecto_txt_id_proyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crear_proyecto_txt_id_proyectoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crear_proyecto_btn_crear_proyecto;
    private javax.swing.JButton crear_proyecto_btn_regresar;
    private javax.swing.JTextArea crear_proyecto_jTextArea_descripcion;
    private javax.swing.JTextField crear_proyecto_txt_duracion;
    private javax.swing.JTextField crear_proyecto_txt_fecha_inicio;
    private javax.swing.JTextField crear_proyecto_txt_id_proyecto;
    private javax.swing.JTextField crear_proyecto_txt_nombre;
    private javax.swing.JTextField crear_proyecto_txt_presupuesto;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel login_lbl_usuario;
    private javax.swing.JLabel login_lbl_usuario1;
    private javax.swing.JLabel login_lbl_usuario2;
    private javax.swing.JLabel login_lbl_usuario3;
    private javax.swing.JLabel login_lbl_usuario4;
    private javax.swing.JLabel login_lbl_usuario5;
    // End of variables declaration//GEN-END:variables
}
